services:
  mongo:
    image: mongo:7
    container_name: mongo-local
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: tfg-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MONGODB_URI: mongodb://root:root@mongo:27017/mydatabase?authSource=admin
      SPRING_MONGODB_URI: mongodb://root:root@mongo:27017/mydatabase?authSource=admin
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo:27017/mydatabase?authSource=admin
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: tfg-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: