spring.application.name=TFG-cultura-api
spring.data.mongodb.uri=mongodb://root:root@localhost:27018/cultura_db?authSource=admin
app.frontend.url=http://localhost:5173
server.port=8080
springdoc.swagger-ui.path=/api/docs
sonar.coverage.exclusions=**/config/**,**/MongoConfiguration.java,**/DatabaseSeeder.java
# Seeder
app.seed.enabled=true
# JWT
jwt.secret=NqFALt52zysAic5Ks57tqYEFPIcDGVMZ
jwt.expiration=86400000