spring.application.name=TFG-cultura-api
spring.data.mongodb.uri=mongodb://root:root@localhost:27018/mydatabase?authSource=admin
spring.data.mongodb.database=mydatabase
app.frontend.url=http://localhost:5173
server.port=8080
springdoc.swagger-ui.path=/api/docs